### ISSUE TITLE
resize labs logo to match others

### ISSUE THREAD

**Issue by eichmann** [data2health/cd2h-labs#1]

**Comment by alexisgraves** [comment]
Here are the .svg and .png logo files I generated from the original for placeholders on the navigation bar if that helps!
[labs_logos.zip](https://github.com/data2health/cd2h-labs/files/2958600/labs_logo.zip)

<img src="https://user-images.githubusercontent.com/12225601/54232556-e4936380-44d8-11e9-9943-af15beff26f7.png" width="150">

**Comment by jmcmurry** [comment]
Thanks @alexisgraves ; Seems like this is done, then yes? I will close; please reopen and clarify if this is not complete.
