### ISSUE TITLE
CIELO link to be added

### ISSUE THREAD

**Issue by tmdillon** [data2health/cd2h-labs#16]
Dave this is the CIELO link for posting to CD2H Labs.   
Our beta site: https://cd2h.cielo.wustl.edu

Our git repo: https://github.com/data2health/cielo

**Comment by mellybelly** [comment]
cielo may not be a priority for CD2H funding right now but it was still funded under CD2H and should be made available in labs. We should try to promote community interest/contributions for all tools in labs imho, and then the community essentially decides what it likes/needs.

**Comment by mellybelly** [comment]
just saying "yes please" :-)

**Comment by eichmann** [comment]
Linked deployed on RD&D card as per Philip.
