### ISSUE TITLE
add project matrix graphic to main landing page with imagemap links to target projects and verticals

### ISSUE THREAD

**Issue by eichmann** [data2health/cd2h-labs#2]

**Comment by eichmann** [comment]
- [x] @mellybelly I think you have the master version of the graphic

- [ ] @alexisgraves once we have the image please create the linkage overlay

**Comment by mellybelly** [comment]
see here: https://github.com/data2health/cd2h-labs/blob/master/CD2H%20CTSA%20org%20structuresV5.pdf

**Comment by eichmann** [comment]
Melissa, your PDF doesn't load in Acrobat or Preview...

**Comment by eichmann** [comment]
project matrix is up as index2.jsp
