### ISSUE TITLE
Script to monitor uptime of referenced apps/resources

### ISSUE THREAD

**Issue by jmcmurry** [data2health/cd2h-labs#23]
Write script to 
- [x] Test for uptime the URLs of each of the referenced apps and resources
- [x] Notify administrator of any outages
- [ ] Log outages over time

**Comment by eichmann** [comment]
This is a job for Jenkins (at least points one and two). Do we really need to log outages?  I'm all for not collecting data that we're not going to use.  Knowing something's offline seems sufficient.

**Comment by eichmann** [comment]
Who (besides me) should be notified of outages?  If I configure the monitors on a per-tool perspective, we can list specific folks for each.

**Comment by eichmann** [comment]
Jenkins configuration online.  Right now it emails Julie and me and texts me.  Feel free to volunteer for notifications!

**Comment by jmcmurry** [comment]
In terms of the log, I think what I'm looking for here is to distinguish between an anomalous outage and a recurring problem. That said, this is already fit for purpose. The log is a low priority. Can close.
