### ISSUE TITLE
Changes RE: http://labs.cd2h.org/labs/, "Current Prototypes from our Teams and our Collaborators:"

### ISSUE THREAD

**Issue by kristiholmes** [data2health/cd2h-labs#24]
RE: http://labs.cd2h.org/labs/, "Current Prototypes from our Teams and our Collaborators:"

1. Please move CD2H project tracking to the bottom. This is mostly internal and not directly impactful to hubs.
2. Please switch the placement of InvenioRDM and OpenVIVO tabs
3. Please consider condensing the other two cores into one section so that they look fuller - not sure if that will work, but would be great for the top of the drop-down to look full.

Let me know if any of this doesn't make sense.  tagging @mellybelly @carsonicator so that they know what I have requested. Thanks!

**Comment by mellybelly** [comment]
i agree with all these suggestions, maybe for the two sparser cores the could be side by side?
