### ISSUE TITLE
solicit URLs for inclusion from project leads

### ISSUE THREAD

**Issue by eichmann** [data2health/cd2h-labs#3]

**Comment by jmcmurry** [comment]
@data2health/projleads this was mentioned on the allhands call today and in the bulletin, but please get the URLS for your working code to Dave asap. The expectation is that all existing code that is deployed should be featured in the labs site before the iDTF meeting. Thanks :)

**Comment by jmcmurry** [comment]
Just to clarify, by "Get the URLs to Dave",  I mean that the best mechanism to do so is to create a ticket in the labs repo [here](https://github.com/data2health/cd2h-labs/issues/new). I will close this ticket as I'm now off of the critical path.
